### PR TITLE
Clean up & clarify the README

### PR DESCRIPTION
**Pull request by jeffbyrnes**
* Add link to the latest released package of the Dictionary
* Fix some grammar in iOS section
* Re-order sections so the “just download it” bit is earlier, b/c that is most useful for most folks

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@ponychicken seems the folks who host the GCIDE git repo are maybe blocking GitHub? I can fetch the submodule just fine locally.

Perhaps we disable the merge requirements temporarily?

**Comment by ponychicken** [comment]
Hi I am on vacation.
I can give you full access in a week.

08.08.2022 16:47:45 Jeff Byrnes ***@***.***>:

**Comment by jeffbyrnes** [comment]
@ponychicken sounds good, thanks!

**Comment by ponychicken** [comment]
had time anyway. you should be able to "Merge without waiting for requirements to be met (bypass branch protections) " now or change the CI steps

**Pull request merged**
