### PR TITLE
Imrove source parsing for WEBSTERONLY

### LINKED ISSUE #29: Some lines in definitions get lost in the output files
Edit: After many hours of of trial and error on my phone with Termux (I don't have a computer with me these days), I managed to convert this new format to Stardict. See the next comment.

During the process, I noted the following issue.

It seems that some lines in definitions get lost in the output files (for example: in template/dict.xml file).

For example, with the word "**happy**", in **srcFiles/CIDE.H**, its original entry is:

```html
<p><ent>Happy</ent><br/
<hw>Hap"py</hw> <pr>(h<acr/p"p<ycr/)</pr>, <pos>a.</pos> <amorph>[<pos>Compar.</pos> <adjf>Happier</adjf> <pr>(-p<icr/*<etil/r)</pr>; <pos>superl.</pos> <adjf>Happiest</adjf>.]</amorph> <ety>[From <er>Hap</er> chance.]</ety> <sn>1.</sn> <def>Favored by hap, luck, or fortune; lucky; fortunate; successful; prosperous; satisfying desire; <as>as, a <ex>happy</ex> expedient; a <ex>happy</ex> effort; a <ex>happy</ex> venture; a <ex>happy</ex> omen.</as></def><br/
[<source>1913 Webster</source>]</p>

<p><q>Chymists have been more <qex>happy</qex> in finding experiments than the causes of them.</q> <rj><qau>Boyle.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><sn>2.</sn> <def>Experiencing the effect of favorable fortune; having the feeling arising from the consciousness of well-being or of enjoyment; enjoying good of any kind, as peace, tranquillity, comfort; contented; joyous; <as>as, <ex>happy</ex> hours, <ex>happy</ex> thoughts</as>.</def><br/
[<source>1913 Webster</source>]</p>

<p><q><qex>Happy</qex> is that people, whose God is the Lord.</q> <rj><qau>Ps. cxliv. 15.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><q>The learned is <qex>happy</qex> Nature to explore,<br/
The fool is <qex>happy</qex> that he knows no more.</q> <rj><qau>Pope.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><sn>3.</sn> <def>Dexterous; ready; apt; felicitous.</def><br/
[<source>1913 Webster</source>]</p>

<p><q>One gentleman is <qex>happy</qex> at a reply, another excels in a in a rejoinder.</q> <rj><qau>Swift.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><cs><col><b>Happy family</b></col>, <cd>a collection of animals of different and hostile propensities living peaceably together in one cage. Used ironically of conventional alliances of persons who are in fact mutually repugnant.</cd> -- <col><b>Happy-go-lucky</b></col>, <cd>trusting to hap or luck; improvident; easy-going.</cd> <ldquo/<xex>Happy-go-lucky</xex> carelessness.<rdquo/  <rj><au>W. Black.</au></rj></cs><br/
[<source>1913 Webster</source>]</p>

```

It is missing the following lines, given that they all have the same **[<source>1913 Webster</source>]**:

```html
<p><q>One gentleman is <qex>happy</qex> at a reply, another excels in a in a rejoinder.</q> <rj><qau>Swift.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><cs><col><b>Happy family</b></col>, <cd>a collection of animals of different and hostile propensities living peaceably together in one cage. Used ironically of conventional alliances of persons who are in fact mutually repugnant.</cd> -- <col><b>Happy-go-lucky</b></col>, <cd>trusting to hap or luck; improvident; easy-going.</cd> <ldquo/<xex>Happy-go-lucky</xex> carelessness.<rdquo/  <rj><au>W. Black.</au></rj></cs><br/
[<source>1913 Webster</source>]</p>

```

See the attached picture to compared with an old format Stardict dictionary data, from [Jsomers link](https://gist.github.com/jsomers/9dd78c8dc7fab071993c)

Websters1913-new-format2

Websters1913-new-format

### LINKED ISSUE #31: Many words are removed instead of only removing PJC definitions
As referenced in https://github.com/ponychicken/WebsterParser/pull/19, the decision to completely exclude PJC is removing some root entries that should still exist.

For example, one of the most important words in the English language, "Coffee" is removed.

In `src/CIDE.C`:

```
<p><ent>Coffee</ent><br/
<hw>Cof"fee</hw> <pr>(k<add/"f<esl/; k<ocr/f"f<esl/; 115)</pr>, <pos>n.</pos> <ety>[Turk. <ets>qahveh</ets>, Ar. <ets>qahuah</ets> wine, coffee, a decoction of berries. Cf. <er>Caf<eacute/</er>.]</ety> <sn>1.</sn> <def>The <ldquo/beans<rdquo/ or <ldquo/berries<rdquo/ (pyrenes) obtained from the drupes of a small evergreen tree of the genus <gen>Coffea</gen>, growing in Abyssinia, Arabia, Persia, and other warm regions of Asia and Africa, and also in tropical America.</def><br/
[<source>1913 Webster</source> <source>+PJC</source>]</p>

<p><sn>2.</sn> <def>The coffee tree.</def><br/
[<source>1913 Webster</source>]</p>

<p><note><hand/ There are several species of the coffee tree, as, <spn>Coffea Arabica</spn>, <spn>Coffea canephora</spn>, <spn>Coffea occidentalis</spn>, and <spn>Coffea Liberica</spn>.  The white, fragrant flowers grow in clusters at the root of the leaves, and the fruit is a red or purple cherrylike drupe, with sweet pulp, usually containing two pyrenes, commercially called <ldquo/beans<rdquo/ or <ldquo/berries<rdquo/.</note><br/
[<source>1913 Webster</source>]</p>

<p><sn>3.</sn> <def>The beverage made by decoction of the roasted and ground berry of the coffee tree.</def><br/
[<source>1913 Webster</source>]</p>

<p><q>They have in Turkey a drink called <qex>coffee</qex>.  . . . This drink comforteth the brain and heart, and helpeth digestion.</q> <rj><qau>Bacon.</qau></rj><br/
[<source>1913 Webster</source>]</p>

<p><sn>4.</sn> <def>a cup of coffee{3}, especially one served in a restaurant; <as>as, we each had two donuts and a <ex>coffee</ex>; three <ex>coffees</ex> to go</as>.</def><br/
[<source>PJC</source>]</p>

<p><sn>5.</sn> <def>a social gathering at which coffee is served, with optional other foods or refreshments.</def><br/
[<source>PJC</source>]</p>

<p><sn>6.</sn> <def>a color ranging from medium brown to dark brown.</def><br/
[<source>PJC</source>]</p>

<p><note><hand/ The use of <xex>coffee</xex> is said to have been introduced into England about 1650, when coffeehouses were opened in Oxford and London.</note><br/
[<source>1913 Webster</source>]</p>

<p><cs><col><b>Coffee bug</b></col> <fld>(Zool.)</fld>, <cd>a species of scale insect (<spn>Lecanium coff<ae/a</spn>), often very injurious to the coffee tree.</cd> -- <col><b>Coffee rat</b></col> <fld>(Zool.)</fld> <cd>See <er>Musang</er>.</cd></cs><br/
[<source>1913 Webster</source>]</p>
```

I agree that the PJC defs like (4) should be removed but because of the addition of the PJC defs, the root entry has a source of `[<source>1913 Webster</source> <source>+PJC</source>]</p>`. The current code now removes the entire Coffee entry because a child definition is PJC and that's noted on the root. See the [Gutenberg version for Letter C](https://www.gutenberg.org/files/661/661-h/661-h.htm) to find the original definition of "Coffee".

I'm happy to open a PR for something like the following change:

```js
      if (! src.text().trim().includes('1913 Webster') &&
          ! src.text().trim().includes('Webster 1913 Suppl.')
      ) {
        return true;
      }
```
This seems to correctly include the root entry of Coffee while removing the PJC definitions but wanted to open for discussion first.

### PR DESCRIPTION
**Pull request by nickwynja**
Drops individual defs if not from Webster (or no source defined), then
drops any words with no defs. Improves more aggressive cleaning of
source tags when in WEBSTERONLY mode.

Also updates the filename to render better in Dictionary.app.

Fixes #29, fixes #31.

### Note:

Two specific words in the source dictionary cause terrible death-spiral loops: "Condorcet's method" and "Lese majesty". The following diff fixes this by removing and adding a `<p>`, respectively. I've reported this issue to the upstream maintainer of GCIDE.

```diff
diff --git a/CIDE.C b/CIDE.C
index a196367..6872414 100644
--- a/CIDE.C
+++ b/CIDE.C
@@ -50715,7 +50715,7 @@ Have ebb and flow <qex>conditioning</qex> their march.</q> <rj><qau>Tenn
yson.</q
 [<source>PJC</source>]</p>

 <p><ent>Condorcet's method</ent><br/
-<p><hw>Condorcet's method</hw> <def>Condorcet's method is one of several pairwise methods, whic
h are great methods for electing people in single-seat elections (president, governor, mayor, et
c.).  Condorcet's method is named after the 18th century election theorist who invented it.  Unl
ike most methods which make you choose the lesser of two evils, Condorcet's method and other pai
rwise methods let you rank the candidates in the order in which you would see them elected.  The
 way the votes are tallied is by computing the results of separate pairwise elections between al
l of the candidates, and the winner is the one that wins a majority in all of the pairwise elect
ions.<br/
+<hw>Condorcet's method</hw> <def>Condorcet's method is one of several pairwise methods, which a
re great methods for electing people in single-seat elections (president, governor, mayor, etc.)
.  Condorcet's method is named after the 18th century election theorist who invented it.  Unlike
 most methods which make you choose the lesser of two evils, Condorcet's method and other pairwi
se methods let you rank the candidates in the order in which you would see them elected.  The wa
y the votes are tallied is by computing the results of separate pairwise elections between all o
f the candidates, and the winner is the one that wins a majority in all of the pairwise election
s.<br/
     The best result of this is that if there is Candidate A on one extreme who pulls 40% of the
 vote, Candidate B in the middle who only pulls 20% of the vote, and Candidate C on the other ex
treme who pulls 40% of the vote, Candidate B will get elected as a compromise. Why? Because in a
 two-way contest between A and B, B would win with 60% of the vote, and in a two-way contest bet
ween B and C, B would also win with 60% of the vote. (Note that if B is a loony billionaire, he
might not be able to win separate pairwise elections against anyone, and this would be reflected
 with Condorcet's method.)<br/
    Condorcet's method lets voters mark their sincere wishes for who they would like to win the
election, without having to consider strategy ("I'd vote for Candidate B, but I'm afraid of wast
ing my vote."). It's really just a logical extension of majority rule when more than two choices
 are involved. Other pairwise methods, such as Copeland's method and Smith's method, have other
desirable characteristics. The best of the pairwise methods is something that is quite debatable
.<br/
 Wait, I've heard of this before...<br/
diff --git a/CIDE.L b/CIDE.L
index 7c86d91..e882aa3 100644
--- a/CIDE.L
+++ b/CIDE.L
@@ -12942,7 +12942,7 @@ To mock the <qex>lewd</qex>, as learn'd in this as they.</q> <rj><qau>Si
r. J. Da
 <p><ent>Lese majesty</ent><br/
 <ent>Leze majesty</ent><br/
 <mhw><hw>Lese` maj"es*ty</hw>, <hw>Leze` maj"es*ty</hw></mhw> <pr>(l<emac/z` m<acr/j"<ecr/s*t<y
cr/)</pr> <pos>n.</pos> <ety>[F. <ets>lese-majest<eacute/</ets>, fr. L. <ets>laesus</ets>, fem.
<ets>laesa</ets>, injured (see <er>Lesion</er>) + <ets>majestas</ets> majesty; that is, <ets>cri
men laesae majestatis</ets>.]</ety> <altsp>[Written also <asp>l<egrave/se majesty</asp>.]</altsp
> <sn>1.</sn> <fld>(Law)</fld> <def>Any crime committed against the sovereign power, or against
a ruler.</def><br/
-[<source>1913 Webster</source>]
+[<source>1913 Webster</source>]</p>
```

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
I built the dictionary using this PR, and Dictionary.app freezes & beachballs when trying to view the “Condorcet's method” entry.

Definitely improvements here, but also clearly doesn’t quite work. I’ll poke & prod some more tomorrow.

**Comment by nickwynja** [comment]
Just to clarify, had you manually implemented the patches to "Condorcet's method" and "Lese majesty" as mentioned in the PR? I can implement an auto-patching mechanism until the fixes are accepted upstream. On my end, "Condorcet's method" ends up being removed from the dictionary since it's a PJC definition.

**Comment by nickwynja** [comment]
I realize now after re-reading the PR that it's not at all clear that those changes need to manually be made, so apologies about that.

**Comment by jeffbyrnes** [comment]
@nickwynja aha! Lemme see if I can figure that out and try again…

**Comment by jeffbyrnes** [comment]
Ok, I get what you mean now, so I’ll stay away from looking at those two definitions 😄

**Comment by jeffbyrnes** [comment]
Works great if I apply that patch locally! I’ve made a few adjustments to this, so I’ll merge my local version of this branch.

Thanks for this!

**Comment by jeffbyrnes** [comment]
Closed via 3375fe69

**Comment by jeffbyrnes** [comment]
Took me a little finagling, but [1.3.6](https://github.com/ponychicken/WebsterParser/releases/tag/1.3.6) is out & includes your changes here. Thanks again!

**Pull request closed without merging**
