### PR TITLE
Tighten up build more, add Webster’s 1913 Supplement entries

### PR DESCRIPTION
**Pull request by jeffbyrnes**
This fixes the `websters-1913.dictionary` package being collapsed into its individual files in the ZIP that’s created.

It also reduces some steps & avoids building twice on pull requests.

[edit]

And, now it also includes the Webster’s 1913 Supplemental entries, in addition to the 1890 entries that have always been included. See eccc6a1 for this change.

From the GCIDE README in srcFiles:

    At the bottom of each paragraph in this dictionary, there is a bracketed and
    tagged "source" indicated.  This tells from where the definition or other
    text in that paragraph came, as follows:

    [<source>1913 Webster</source>]
      =  From the original 1890 dictionary.
    [<source>Webster 1913 Suppl.</source>]
      =  From the 1913 "New Words" supplement to the Webster.
    [<source>WordNet 1.5</source>]
      =  From the WordNet on-line semantic network.
    [<source>Century Dict. 1906.</source>]
      =  From the Century Dictionary published in 1906, especially from
              the "proper Names" supplement (volume IX).
                                         published
    [<source>XXX</source>]
       = Added by one of the volunteers.

### CODE REVIEW

**Comment by jeffbyrnes** [comment]
@ponychicken this checks out; if you go to the build & download the ZIP artifact, you end up unzipping a `websters-1913.dictionary` package, instead of a directory with the files that make up the package.

**Comment by j-f1** [comment]
Neat! Do you know approximately how many more entries there are?

**Comment by jeffbyrnes** [comment]
Good question! A did a quick search for `<source>Webster 1913 Suppl.</source>` in `srcFiles/`, and it looks like it adds about 5000 entries 😲

**Comment by jeffbyrnes** [comment]
This has been working great for me for a few days now, gonna merge it in & cut a new release.

**Comment by ponychicken** [comment]
Looks good!
I had it on my list to merge it today, one less thing to do :)

**Pull request merged**
