### PR TITLE
Add more to codeTables

### PR DESCRIPTION
**Pull request by jeffbyrnes**
Noticed in at least one definition that these were not rendered correctly, and have a single character version.

### CODE REVIEW

**Review by ponychicken — APPROVED** [review]

**Comment by ponychicken** [comment]
I had added some more entities in the meantime, maybe you could rebase your changes.

**Comment by jeffbyrnes** [comment]
@ponychicken definitely will.

However, something about the new submodule version of GCIDE is breaking the generation of the XML. I’m trying to puzzle it out now.

**Comment by jeffbyrnes** [comment]
Well, not sure what’s up with the build now; it appears to just stop after it has “Parsed” the last file, and does not move on to “Postprocessing”, but it doesn‘t throw an error.

That said, it builds for me locally, so if it builds for you, maybe this is good to go, and we can debug the build later 🙂

**Comment by ponychicken** [comment]
Ja, I don't know whats up with this build. Seems very fragile. For some builds it was also failing, saying it got an 502 when fetching the git submodule, and when i tried it locally a minute later it worked..

**Comment by jeffbyrnes** [comment]
Hmmm. Well, we can keep poking, but as long as we can build & release manually, it’s all good.

**Pull request merged**
